#!/usr/bin/env bash
# Example-module validation. Stages the committed examples/ modules into a throwaway
# git repo, installs them with usm in a fully sandboxed HOME/USM_CONFIG/USM_DATA, and
# asserts the real end-to-end result: dependency auto-pull + ordering, rc assembly +
# symlink, and that the compiled loader sources cleanly in BOTH bash and zsh, defining
# the module's aliases and functions. Invoked by test/run.sh; also runnable directly.
#
# Never touches the real $HOME. The usm repo has no commits/tags, so examples are
# staged into a temp repo here rather than installed from the repo in place.
set -u

USM_ROOT="$(cd -P "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
USM_BIN="$USM_ROOT/bin/usm"
EXAMPLES="$USM_ROOT/examples"

PASS=0; FAIL=0
ok()   { PASS=$((PASS + 1)); printf '  ok   %s\n' "$1"; }
bad()  { FAIL=$((FAIL + 1)); printf '  FAIL %s\n' "$1"; }
check(){ if [ "$2" = "$3" ]; then ok "$1"; else bad "$1 (want [$3] got [$2])"; fi; }
grep_ok() { if grep -qF "$2" "$3" 2>/dev/null; then ok "$1"; else bad "$1 (missing [$2] in $3)"; fi; }

TMP="$(mktemp -d "${TMPDIR:-/tmp}/usm-examples.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT

export HOME="$TMP/home"; mkdir -p "$HOME"
export USM_CONFIG="$TMP/cfg"
export USM_DATA="$TMP/data"
export USM_VERBOSE=0
export GIT_AUTHOR_NAME=usm GIT_AUTHOR_EMAIL=usm@test
export GIT_COMMITTER_NAME=usm GIT_COMMITTER_EMAIL=usm@test

usm() { "$USM_BIN" "$@"; }

LOCK="$USM_DATA/lock.yaml"
CFG="$USM_CONFIG/config.yaml"
LOAD="$USM_DATA/compiled/load.sh"

# ---- Stage the committed examples into a throwaway repo (one repo, two subdirs) ----
REPO="$TMP/shell-modules"
mkdir -p "$REPO"
cp -R "$EXAMPLES/git-workflow" "$REPO/git-workflow"
cp -R "$EXAMPLES/psql"         "$REPO/psql"
# psql's manifest ships a placeholder requires.source; rewrite it to THIS repo so the
# intra-repo dependency resolves offline (this is what a publisher's real URL becomes).
SRC="$REPO" yq -i '.requires[0].source = strenv(SRC)' "$REPO/psql/usm.yaml"
git -C "$REPO" init -q
git -C "$REPO" symbolic-ref HEAD refs/heads/main
git -C "$REPO" add -A
git -C "$REPO" commit -q -m "example modules"
git -C "$REPO" tag v1.0.0

printf '== examples: init + install psql (requires must auto-pull git-workflow) ==\n'
usm init >/dev/null 2>&1
usm install "$REPO" --subdir psql --version '>=1.0.0' >/dev/null 2>&1

check "both example modules resolved"   "$(yq '.modules | length' "$LOCK")" 2
check "git-workflow auto-pulled as dep"  "$(NM=git-workflow yq '[.modules[]|select(.name==strenv(NM))]|length' "$LOCK")" 1
check "psql requires git-workflow"       "$(NM=psql yq '.modules[]|select(.name==strenv(NM))|.requires|join(",")' "$LOCK")" git-workflow
check "psql resolved to tag v1.0.0"      "$(NM=psql yq '.modules[]|select(.name==strenv(NM))|.ref' "$LOCK")" v1.0.0

printf '== examples: load order (dependency before dependent) ==\n'
GW_LINE="$(grep -n 'git-workflow/fragments/functions.sh' "$LOAD" | cut -d: -f1)"
PS_LINE="$(grep -n 'psql/fragments/env.sh' "$LOAD" | cut -d: -f1)"
check "git-workflow sourced before psql" "$( [ -n "$GW_LINE" ] && [ "$GW_LINE" -lt "$PS_LINE" ] && echo yes || echo no )" yes

printf '== examples: rc assembly + symlink ==\n'
check "config.rc_files derived = [psqlrc]" "$(yq -o=json -I=0 '.rc_files' "$CFG")" '["psqlrc"]'
grep_ok "psqlrc has fragment content"      "\pset null '[null]'" "$USM_DATA/rc/psqlrc"
grep_ok "psqlrc has generated header"      "generated by usm" "$USM_DATA/rc/psqlrc"
check "~/.psqlrc links to staged rc"       "$(readlink "$HOME/.psqlrc")" "$USM_DATA/rc/psqlrc"

printf '== examples: usm list shows both modules ==\n'
LIST_OUT="$(usm list 2>/dev/null)"
check "list shows git-workflow" "$(printf '%s\n' "$LIST_OUT" | grep -c '^git-workflow')" 1
check "list shows psql"         "$(printf '%s\n' "$LIST_OUT" | grep -c '^psql')" 1

printf '== examples: compiled loader sources cleanly in bash (interactive-alias mode) ==\n'
# bash disables alias expansion in non-interactive shells, so enable it to mirror the
# interactive shells usm actually loads into; functions/env need no such flag.
BASH_OUT="$(bash --norc -c 'shopt -s expand_aliases; set -e; . "'"$LOAD"'"
  alias gs >/dev/null && printf "gs "
  alias gl >/dev/null && printf "gl "
  type git_current_branch >/dev/null 2>&1 && printf "git_current_branch "
  type pgdev >/dev/null 2>&1 && printf "pgdev "
  printf "PSQL_PAGER=%s" "$PSQL_PAGER"' 2>&1)"; BASH_RC=$?
check "bash sources loader without error" "$BASH_RC" 0
check "bash defines gs+gl+funcs+env"      "$BASH_OUT" "gs gl git_current_branch pgdev PSQL_PAGER=less -SXF"

printf '== examples: compiled loader sources cleanly in zsh ==\n'
ZSH_OUT="$(zsh -f -c 'set -e; . "'"$LOAD"'"
  alias gs >/dev/null && printf "gs "
  alias gl >/dev/null && printf "gl "
  type git_current_branch >/dev/null 2>&1 && printf "git_current_branch "
  type pgdev >/dev/null 2>&1 && printf "pgdev "
  printf "PSQL_PAGER=%s" "$PSQL_PAGER"' 2>&1)"; ZSH_RC=$?
check "zsh sources loader without error" "$ZSH_RC" 0
check "zsh defines gs+gl+funcs+env"      "$ZSH_OUT" "gs gl git_current_branch pgdev PSQL_PAGER=less -SXF"

printf '== examples: doctor is green on the example install ==\n'
usm doctor >/dev/null 2>&1; DOC_RC=$?
check "doctor exits 0 on example install" "$DOC_RC" 0

printf '\n== examples summary ==\n'
printf 'EXAMPLES PASS=%s FAIL=%s\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
