# Compile: resolve config.yaml into lock.yaml (via lib/core/resolve.sh), then emit
# compiled/load.sh, assemble rc files, and refresh ~/.<name> links from that lock.
# The semver/tag helpers below (_usm_ver_ge, _usm_pick_tag) are reused by the resolver.

# True iff $1 is a valid 3-component numeric semver (X.Y.Z, no leading 'v'). Anything
# else (too few/many components, empty, non-numeric) is rejected so it never reaches
# the comparator. This is the single gate the tag filter uses.
_usm_is_semver() {
  local v="$1" a b c rest
  case "$v" in '' | .* | *. | *[!0-9.]*) return 1 ;; esac
  IFS=. read -r a b c rest <<EOF
$v
EOF
  [ -z "$rest" ] || return 1                       # reject 4+ components (1.2.3.4)
  [ -n "$a" ] && [ -n "$b" ] && [ -n "$c" ]        # require exactly three
}

# a >= b for dotted numeric versions (X.Y.Z), bash 3.2-safe (no sort -V). Any leftover
# 4th+ field is captured into a throwaway var and any non-numeric component defaults to
# 0, so the comparator NEVER leaks a raw `[: integer expression expected` to stderr,
# regardless of input (defense in depth atop the _usm_is_semver tag filter).
_usm_ver_ge() {
  local a1 a2 a3 b1 b2 b3 _rest
  IFS=. read -r a1 a2 a3 _rest <<EOF
$1
EOF
  IFS=. read -r b1 b2 b3 _rest <<EOF
$2
EOF
  case "$a1" in '' | *[!0-9]*) a1=0 ;; esac
  case "$a2" in '' | *[!0-9]*) a2=0 ;; esac
  case "$a3" in '' | *[!0-9]*) a3=0 ;; esac
  case "$b1" in '' | *[!0-9]*) b1=0 ;; esac
  case "$b2" in '' | *[!0-9]*) b2=0 ;; esac
  case "$b3" in '' | *[!0-9]*) b3=0 ;; esac
  [ "$a1" -ne "$b1" ] && { [ "$a1" -gt "$b1" ]; return; }
  [ "$a2" -ne "$b2" ] && { [ "$a2" -gt "$b2" ]; return; }
  [ "$a3" -ge "$b3" ]
}

# Highest v* tag satisfying an optional lower bound. Prints the tag (e.g. v1.2.0) or
# nothing. With an empty bound, prints the highest valid semver tag. Tags that aren't
# valid X.Y.Z (e.g. v1.2.3.4) are ignored outright — they never reach the comparator.
_usm_pick_tag() {
  local dir="$1" bound="$2" t v best="" bestv=""
  while IFS= read -r t; do
    [ -z "$t" ] && continue
    v="${t#v}"
    _usm_is_semver "$v" || continue                # keep valid X.Y.Z only
    if [ -n "$bound" ]; then _usm_ver_ge "$v" "$bound" || continue; fi
    if [ -z "$best" ] || _usm_ver_ge "$v" "$bestv"; then best="$t"; bestv="$v"; fi
  done <<EOF
$(usm_git_tags "$dir")
EOF
  printf '%s' "$best"
}

# Is fragment $3 disabled for module $2 in config $1 (overrides.<name>.disable_fragments)?
_usm_frag_disabled() {
  local hit
  hit="$(NM="$2" FR="$3" yq '[.overrides[strenv(NM)].disable_fragments // [] | .[] | select(. == strenv(FR))] | length' "$1" 2>/dev/null)"
  [ "${hit:-0}" != 0 ]
}

# Natural comment token for a generated rc file.
_usm_rc_comment() {
  case "$1" in
    psqlrc) printf '%s' '--' ;;
    *)      printf '%s' '#' ;;
  esac
}

# Full compile pipeline over the current config.yaml. Resolution (graph, versions,
# requires edges, ordering, conflict/cycle surfacing) lives in lib/core/resolve.sh;
# _usm_resolve writes lock.yaml in final load order. Everything downstream (load.sh,
# rc assembly, links) reads that lock unchanged.
usm_compile() {
  usm_ensure_dirs
  local cfg lock
  cfg="$(usm_config_file)"; lock="$(usm_lock_file)"
  [ -f "$cfg" ] || { usm_err "no config.yaml; run 'usm init' first"; return 1; }

  _usm_resolve "$cfg" "$lock" || return 1
  _usm_write_load "$lock" "$cfg"
  _usm_assemble_rc "$lock" "$cfg"
  usm_vlog "compiled $(yq '.modules | length' "$lock") module(s)"
}

# Emit compiled/load.sh: absolute source lines for shell fragments, in lock order.
_usm_write_load() {
  local lock="$1" cfg="$2" out tmp n i cache
  out="$(usm_compiled_dir)/load.sh"; tmp="$out.tmp.$$"
  cache="$(usm_cache_dir)"
  n="$(yq '.modules | length' "$lock")"
  {
    printf '# GENERATED by usm — do not edit. Sourced at shell startup.\n'
    i=0
    while [ "$i" -lt "$n" ]; do
      local name path frag
      name="$(yq ".modules[$i].name" "$lock")"
      path="$(yq ".modules[$i].path" "$lock")"
      while IFS= read -r frag; do
        [ -z "$frag" ] && continue
        _usm_frag_disabled "$cfg" "$name" "$frag" && continue
        printf '. "%s"\n' "$cache/$path/$frag"
      done <<EOF
$(yq ".modules[$i].shell // [] | .[]" "$lock")
EOF
      i=$((i + 1))
    done
  } >"$tmp"
  mv "$tmp" "$out"
}

# Assemble every rc file contributed by any module; set config.rc_files to that union;
# refresh ~/.<name> symlinks; unlink rc files no longer contributed.
_usm_assemble_rc() {
  local lock="$1" cfg="$2" rcdir names name produced="" d base
  rcdir="$(usm_rc_dir)"; mkdir -p "$rcdir"

  names="$(yq '[.modules[] | (.rc // {}) | keys | .[]] | unique | .[]' "$lock" 2>/dev/null)"

  # Rewrite config.rc_files as the union of rc names modules contribute.
  yq -i '.rc_files = []' "$cfg"
  while IFS= read -r name; do
    [ -z "$name" ] && continue
    NM="$name" yq -i '.rc_files += [strenv(NM)]' "$cfg"
  done <<EOF
$names
EOF

  while IFS= read -r name; do
    [ -z "$name" ] && continue
    if _usm_assemble_one "$name" "$lock" "$cfg"; then produced="$produced $name"; fi
  done <<EOF
$names
EOF

  # Clean up rc files USM previously staged but no module contributes to anymore.
  if [ -d "$rcdir" ]; then
    for d in "$rcdir"/*; do
      [ -f "$d" ] || continue
      base="$(basename "$d")"
      case " $produced " in
        *" $base "*) : ;;
        *) _usm_unlink_home_rc "$base" "$d" ;;
      esac
    done
  fi
}

# Assemble one rc file from its (non-disabled) fragments, in lock order. Returns 0 if
# any fragment contributed (file written + linked), else 1 (staged file/link removed).
_usm_assemble_one() {
  local name="$1" lock="$2" cfg="$3" rcdir out tmp comment n i contributed=0 cache
  rcdir="$(usm_rc_dir)"; cache="$(usm_cache_dir)"
  out="$rcdir/$name"; tmp="$out.tmp.$$"
  comment="$(_usm_rc_comment "$name")"
  printf '%s generated by usm — do not edit\n' "$comment" >"$tmp"

  n="$(yq '.modules | length' "$lock")"
  i=0
  while [ "$i" -lt "$n" ]; do
    local mname mpath frag abs
    mname="$(yq ".modules[$i].name" "$lock")"
    mpath="$(yq ".modules[$i].path" "$lock")"
    while IFS= read -r frag; do
      [ -z "$frag" ] && continue
      _usm_frag_disabled "$cfg" "$mname" "$frag" && continue
      abs="$cache/$mpath/$frag"
      if [ -f "$abs" ]; then
        cat "$abs" >>"$tmp"
        printf '\n' >>"$tmp"
        contributed=1
      fi
    done <<EOF
$(NM="$name" yq ".modules[$i].rc[strenv(NM)] // [] | .[]" "$lock")
EOF
    i=$((i + 1))
  done

  if [ "$contributed" = 1 ]; then
    mv "$tmp" "$out"
    _usm_link_home_rc "$name" "$out"
    return 0
  fi
  rm -f "$tmp"
  _usm_unlink_home_rc "$name" "$out"
  return 1
}

# Point ~/.<name> at the staged rc file. Back up a pre-existing real file once
# (never clobbering an existing backup); replace a foreign/stale symlink silently.
_usm_link_home_rc() {
  local name="$1" target="$2" link bak
  link="$HOME/.$name"; bak="$link.usm-backup"
  if [ -L "$link" ]; then
    [ "$(readlink "$link")" = "$target" ] && return 0
    rm -f "$link"; ln -s "$target" "$link"; return 0
  fi
  if [ -e "$link" ]; then
    if [ -e "$bak" ] || [ -L "$bak" ]; then
      usm_warn "$link exists and $bak already present; leaving it, not linking"
      return 0
    fi
    mv "$link" "$bak"
    usm_warn "moved existing $link to $bak"
  fi
  ln -s "$target" "$link"
}

# Reverse _usm_link_home_rc: drop the staged file, remove our symlink, restore backup.
_usm_unlink_home_rc() {
  local name="$1" target="$2" link bak
  link="$HOME/.$name"; bak="$link.usm-backup"
  rm -f "$target"
  if [ -L "$link" ] && [ "$(readlink "$link")" = "$target" ]; then
    rm -f "$link"
    if [ -e "$bak" ] || [ -L "$bak" ]; then
      mv "$bak" "$link"
      usm_warn "restored $link from $bak"
    fi
  fi
}
